language: go
matrix:
  include:
    - go: "1.10"
      install: go get -t ./...
      script: go test -v -short -cover -benchtime 10ms -bench . -benchmem ./...
    - go: "1.11"
      install: GO111MODULE=on go get ./...
      script: GO111MODULE=on go test -v -short -cover -benchtime 10ms -bench . -benchmem ./...
    - go: "1.12"
      install: GO111MODULE=on go get ./...
      script: GO111MODULE=on go test -v -short -cover -benchtime 10ms -bench . -benchmem ./...
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
