version: "2.1"

services:
  gandalf:
    build: ../../
    volumes:
      - ../../:/go/src/github.com/JumboInteractiveLimited/Gandalf
      - mmock:/mmock
    working_dir: /go/src/github.com/JumboInteractiveLimited/Gandalf/examples/prototype
    command: go test -v -bench . -benchmem -gandalf.colour -gandalf.mock-dest http://mock:8082 -gandalf.provider-host mock:8080 github.com/JumboInteractiveLimited/Gandalf/examples/prototype

  mock:
    image: jordimartin/mmock
    command: -server-port 8080
    volumes:
      - mmock:/config

volumes:
  mmock:
